#!/bin/sh

hdftoolpath=/usr/lib/enigma2/python/Plugins/Extensions/HDF-Toolbox/scripts
toolscfg=/usr/lib/enigma2/python/Plugins/Extensions/HDF-Toolbox/menu/tools.cfg

# after plugin hdftoolbox update is 'User menu' off
# you have to reboot your box
# yes/no
autogenrc=no

cp genstbtoolmenu.sh ${hdftoolpath}
chmod 755 ${hdftoolpath}/genstbtoolmenu.sh

if ! grep Generate $toolscfg >/dev/null;then
echo "Generate User tools..."
sed -i '/M:main:Return to Main Menu/i\C:menu\/tools:Generate User Tools Menu:scripts\/genstbtoolmenu.sh' ${toolscfg}
fi

if [ "$autogenrc" = "yes" ];then
ln -sf ${hdftoolpath}/genstbtoolmenu.sh /etc/rc3.d/S20genusertoolmenu
fi
